name: ${project.name}
version: ${project.version}
main: dev.proflix.holodropsx.Main
api-version: 1.13
authors: [_ProfliX_]
description: ${project.description}
website: ${project.url}
commands:
  hdxreload:
    usage: /<command>
    description: Reload the config
    permission: holodrops.reload
    permission-message: "§c§lHoloDropsX §r§cRequired permission: <permission>"
    aliases: [hdr]
  hdxcheck:
    usage: /<command>
    description: Check for missing items in the config
    permission: holodrops.check
    permission-message: "§c§lHoloDropsX §r§cRequired permission: <permission>"
    aliases: [hdc]
permissions:
  holodropsx.reload:
    description: Allows the ability to reload the config
    default: op
  holodropsx.check:
    description: Check for missing items in the config
    default: op